title: GitHub Pages Demo
description: A demonstration of GitHub Pages with automatic navigation
theme: minima
url: "https://massyn.github.io/pages/"
baseurl: "https://massyn.github.io/pages/"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md